### ISSUE TITLE
TypeError: Cannot destructure property 'setValues' of 'Object(...)(...)' as it is undefined.

### ISSUE THREAD

**Issue by Njokosi** [satansdeer/ultimate-react-hook-form-form#1]
Geting cannot destructure property set values of undefined on 

DataContext.js
> const { setValues, data } = useData();  

 "dependencies": {
    "next": "10.0.5",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-hook-form": "^6.15.4",
    "yup": "^0.32.9"
  },

![image](https://user-images.githubusercontent.com/75541922/109384136-e6d86d80-78fb-11eb-9fc8-9afffa60bbc6.png)

**Comment by satansdeer** [comment]
@all-contributors please add @Njokosi for bug

**Comment by satansdeer** [comment]
@Njokosi there is no such file `PropertyLocation` in this project, are you having this issue in your project?

**Comment by satansdeer** [comment]
I've tested the app manually, wasn't able to reproduce

**Comment by smitd21** [comment]
In the _app.js you have to wrap the Component with DataProvider

import { DataProvider } from './DataContext'; or './Context/DataContext' (wherever your DataContext file is)
<DataProvider>
        <Component {...pageProps} />
</DataProvider>
